<?php
/**
 * Author: 烽行天下
 * Date: 2018\11\3 0001
 * Time: 16:39
 * QQ: 233238526
 */

function book_sites_node_info(){
  return array(
    'book_sites' => array(
      'name' => t('网站图书官网'),
      'description' => t('添加网站网站图书官网内容'),
      'base' => 'book_sites',
      'has_title' => TRUE,
      'title_label' => t('标题'),
      'help' => t('网站图书官网帮助信息'),
    ),
  );
}

function book_sites_permission(){
  return array(
    'create book_sites' => array(
      'title' => t('创建网站图书官网'),
      'description' => t('这里打勾用户可以创建网站图书官网'),
    ),
    'edit own book_sites' => array(
      'title' => t('只能编辑自己发布的网站图书官网'),
      'description' => t('这里打勾用户可以编辑自己发布的网站图书官网'),
    ),
    'edit any book_sites' => array(
      'title' => t('可以编辑任何人发布的网站图书官网'),
      'description' => t('这里打勾用户可以编辑任何人发布的网站图书官网'),
    ),
    'delete own book_sites' => array(
      'title' => t('删除自己的网站图书官网'),
      'description' => t('用户只能删除自己的网站图书官网'),
    ),
    'delete any book_sites' => array(
      'title' => t('删除任何人发的的网站图书官网'),
      'description' => t('用户能删除任何人发布的网站图书官网'),
    ),
  );
}

function book_sites_node_access($op,$node,$account){
  $is_author = $account->id == $node->id;
  switch ($op){
    case 'create':
      if(user_access('create book_sites',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'update':
      if($is_author && user_access('edit own book_sites',$account)||user_access('edit any book_sites',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'delete':
      if($is_author && user_access('delete own book_sites',$account)||user_access('delete any book_sites',$account)){
        return NODE_ACCESS_ALLOW;
      }
  }
}


function book_sites_form($node,$form_state){
  return node_content_form($node,$form_state);
}
