<?php
/**
 * Author: 烽行天下
 * Date: 2018\11\3 0001
 * Time: 16:39
 * QQ: 233238526
 */

function feature_server_node_info(){
  return array(
    'feature_server' => array(
      'name' => t('特色服务'),
      'description' => t('添加网站特色服务内容'),
      'base' => 'feature_server',
      'has_title' => TRUE,
      'title_label' => t('标题'),
      'help' => t('特色服务帮助信息'),
    ),
  );
}

function feature_server_permission(){
  return array(
    'create feature_server' => array(
      'title' => t('创建特色服务'),
      'description' => t('这里打勾用户可以创建特色服务'),
    ),
    'edit own feature_server' => array(
      'title' => t('只能编辑自己发布的特色服务'),
      'description' => t('这里打勾用户可以编辑自己发布的特色服务'),
    ),
    'edit any feature_server' => array(
      'title' => t('可以编辑任何人发布的特色服务'),
      'description' => t('这里打勾用户可以编辑任何人发布的特色服务'),
    ),
    'delete own feature_server' => array(
      'title' => t('删除自己的特色服务'),
      'description' => t('用户只能删除自己的特色服务'),
    ),
    'delete any feature_server' => array(
      'title' => t('删除任何人发的的特色服务'),
      'description' => t('用户能删除任何人发布的特色服务'),
    ),
  );
}

function feature_server_node_access($op,$node,$account){
  $is_author = $account->id == $node->id;
  switch ($op){
    case 'create':
      if(user_access('create feature_server',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'update':
      if($is_author && user_access('edit own feature_server',$account)||user_access('edit any feature_server',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'delete':
      if($is_author && user_access('delete own feature_server',$account)||user_access('delete any feature_server',$account)){
        return NODE_ACCESS_ALLOW;
      }
  }
}


function feature_server_form($node,$form_state){
  return node_content_form($node,$form_state);
}
