<?php
/**
 * Author: 烽行天下
 * Date: 2018\11\3 0001
 * Time: 16:39
 * QQ: 233238526
 */

function recommend_node_info(){
  return array(
    'recommend' => array(
      'name' => t('重点推荐'),
      'description' => t('添加网站重点推荐内容'),
      'base' => 'recommend',
      'has_title' => TRUE,
      'title_label' => t('标题'),
      'help' => t('重点推荐帮助信息'),
    ),
  );
}

function recommend_permission(){
  return array(
    'create recommend' => array(
      'title' => t('创建重点推荐'),
      'description' => t('这里打勾用户可以创建重点推荐'),
    ),
    'edit own recommend' => array(
      'title' => t('只能编辑自己发布的重点推荐'),
      'description' => t('这里打勾用户可以编辑自己发布的重点推荐'),
    ),
    'edit any recommend' => array(
      'title' => t('可以编辑任何人发布的重点推荐'),
      'description' => t('这里打勾用户可以编辑任何人发布的重点推荐'),
    ),
    'delete own recommend' => array(
      'title' => t('删除自己的重点推荐'),
      'description' => t('用户只能删除自己的重点推荐'),
    ),
    'delete any recommend' => array(
      'title' => t('删除任何人发的的重点推荐'),
      'description' => t('用户能删除任何人发布的重点推荐'),
    ),
  );
}

function recommend_node_access($op,$node,$account){
  $is_author = $account->id == $node->id;
  switch ($op){
    case 'create':
      if(user_access('create recommend',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'update':
      if($is_author && user_access('edit own recommend',$account)||user_access('edit any recommend',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'delete':
      if($is_author && user_access('delete own recommend',$account)||user_access('delete any recommend',$account)){
        return NODE_ACCESS_ALLOW;
      }
  }
}


function recommend_form($node,$form_state){
  return node_content_form($node,$form_state);
}
