<?php
/**
 * Author: 烽行天下
 * Date: 2018\11\3 0001
 * Time: 16:39
 * QQ: 233238526
 */

function server_guide_node_info(){
  return array(
    'server_guide' => array(
      'name' => t('服务指南'),
      'description' => t('添加网站服务指南内容'),
      'base' => 'server_guide',
      'has_title' => TRUE,
      'title_label' => t('标题'),
      'help' => t('服务指南帮助信息'),
    ),
  );
}

function server_guide_permission(){
  return array(
    'create server_guide' => array(
      'title' => t('创建服务指南'),
      'description' => t('这里打勾用户可以创建服务指南'),
    ),
    'edit own server_guide' => array(
      'title' => t('只能编辑自己发布的服务指南'),
      'description' => t('这里打勾用户可以编辑自己发布的服务指南'),
    ),
    'edit any server_guide' => array(
      'title' => t('可以编辑任何人发布的服务指南'),
      'description' => t('这里打勾用户可以编辑任何人发布的服务指南'),
    ),
    'delete own server_guide' => array(
      'title' => t('删除自己的服务指南'),
      'description' => t('用户只能删除自己的服务指南'),
    ),
    'delete any server_guide' => array(
      'title' => t('删除任何人发的的服务指南'),
      'description' => t('用户能删除任何人发布的服务指南'),
    ),
  );
}

function server_guide_node_access($op,$node,$account){

  $is_author = $account->uid == $node->uid;
  switch ($op){
    case 'create':
      if(user_access('create server_guide',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'update':
      if($is_author && user_access('edit own server_guide',$account)||user_access('edit any server_guide',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'delete':
      if($is_author && user_access('delete own server_guide',$account)||user_access('delete any server_guide',$account)){
        return NODE_ACCESS_ALLOW;
      }
  }
}


function server_guide_form($node,$form_state){
  return node_content_form($node,$form_state);
}
