<?php
/**
 * Author: 烽行天下
 * Date: 2018\11\3 0001
 * Time: 16:39
 * QQ: 233238526
 */

function resources_node_info(){
  return array(
    'resources' => array(
      'name' => t('资源导航'),
      'description' => t('添加网站资源导航内容'),
      'base' => 'resources',
      'has_title' => TRUE,
      'title_label' => t('标题'),
      'help' => t('请填写正确的链接及图片'),
    ),
  );
}

function resources_permission(){
  return array(
    'create resources' => array(
      'title' => t('创建资源导航'),
      'description' => t('这里打勾用户可以创建资源导航'),
    ),
    'edit own resources' => array(
      'title' => t('只能编辑自己发布的资源导航'),
      'description' => t('这里打勾用户可以编辑自己发布的资源导航'),
    ),
    'edit any resources' => array(
      'title' => t('可以编辑任何人发布的资源导航'),
      'description' => t('这里打勾用户可以编辑任何人发布的资源导航'),
    ),
    'delete own resources' => array(
      'title' => t('删除自己的资源导航'),
      'description' => t('用户只能删除自己的资源导航'),
    ),
    'delete any resources' => array(
      'title' => t('删除任何人发布的资源导航'),
      'description' => t('用户能删除任何人发布的资源导航'),
    ),
  );
}

function resources_node_access($op,$node,$account){
  $is_author = $account->uid == $node->uid;
  switch ($op){
    case 'create':
      if(user_access('create resources',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'update':
      if($is_author && user_access('edit own resources',$account)||user_access('edit any resources',$account)){
        return NODE_ACCESS_ALLOW;
      }
    case 'delete':
      if($is_author && user_access('delete own resources',$account)||user_access('delete any resources',$account)){
        return NODE_ACCESS_ALLOW;
      }
  }
}


function resources_form($node,$form_state){
  return node_content_form($node,$form_state);
}
